// <auto-generated />
using System;
using HelpDesk.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace HelpDesk.Persistence.Migrations
{
    [DbContext(typeof(HelpDeskDbContext))]
    [Migration("20221220101355_init")]
    partial class init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.32")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("HelpDesk.Persistence.Models.SupportDepartment", b =>
                {
                    b.Property<Guid>("SupportDepartmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("SupportDepartmentId");

                    b.ToTable("SupportDepartments");

                    b.HasData(
                        new
                        {
                            SupportDepartmentId = new Guid("1d5b9219-9b8c-4996-8a35-51a27feaa74b"),
                            Name = "Backend"
                        },
                        new
                        {
                            SupportDepartmentId = new Guid("dee22e09-d91c-4037-8ad5-dd4213efe33f"),
                            Name = "Catalog"
                        },
                        new
                        {
                            SupportDepartmentId = new Guid("122a1127-6afb-4cc6-976e-148eed423dcd"),
                            Name = "Checkout"
                        });
                });

            modelBuilder.Entity("HelpDesk.Persistence.Models.SupportRequest", b =>
                {
                    b.Property<Guid>("SupportRequestId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasColumnType("ntext");

                    b.Property<int>("RequestStatus")
                        .HasColumnType("int");

                    b.Property<string>("Subject")
                        .HasColumnType("nvarchar(256)");

                    b.Property<Guid>("SupportDepartmentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("SupportSpecialistId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("SupportRequestId");

                    b.HasIndex("SupportDepartmentId");

                    b.HasIndex("SupportSpecialistId");

                    b.ToTable("SupportRequests");
                });

            modelBuilder.Entity("HelpDesk.Persistence.Models.SupportSpecialist", b =>
                {
                    b.Property<Guid>("SupportSpecialistId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(256)");

                    b.Property<Guid>("SupportDepartmentId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("SupportSpecialistId");

                    b.HasIndex("SupportDepartmentId");

                    b.ToTable("SupportSpecialists");

                    b.HasData(
                        new
                        {
                            SupportSpecialistId = new Guid("0389124d-f199-4856-b965-2d38184cc0e8"),
                            Name = "Adam",
                            SupportDepartmentId = new Guid("1d5b9219-9b8c-4996-8a35-51a27feaa74b")
                        },
                        new
                        {
                            SupportSpecialistId = new Guid("61a01264-0d20-46f0-bcd1-36cd20a41123"),
                            Name = "Rayan",
                            SupportDepartmentId = new Guid("1d5b9219-9b8c-4996-8a35-51a27feaa74b")
                        },
                        new
                        {
                            SupportSpecialistId = new Guid("18f522b6-697d-4c96-ae91-018d3374ed14"),
                            Name = "Yurena",
                            SupportDepartmentId = new Guid("1d5b9219-9b8c-4996-8a35-51a27feaa74b")
                        },
                        new
                        {
                            SupportSpecialistId = new Guid("c95501a5-b529-4caa-a199-98da01e3ccfd"),
                            Name = "Antía",
                            SupportDepartmentId = new Guid("dee22e09-d91c-4037-8ad5-dd4213efe33f")
                        },
                        new
                        {
                            SupportSpecialistId = new Guid("fd782f05-2e58-4367-bd4c-e734fdcdedc3"),
                            Name = "Irati",
                            SupportDepartmentId = new Guid("dee22e09-d91c-4037-8ad5-dd4213efe33f")
                        },
                        new
                        {
                            SupportSpecialistId = new Guid("7fd58309-c943-42f6-9355-1c6c0be87d90"),
                            Name = "Xosé",
                            SupportDepartmentId = new Guid("dee22e09-d91c-4037-8ad5-dd4213efe33f")
                        },
                        new
                        {
                            SupportSpecialistId = new Guid("aacb0189-d28c-40f9-97c5-dd5073961771"),
                            Name = "Martina",
                            SupportDepartmentId = new Guid("122a1127-6afb-4cc6-976e-148eed423dcd")
                        },
                        new
                        {
                            SupportSpecialistId = new Guid("c6fdf17d-a495-4685-8eff-1d95d97fdf59"),
                            Name = "Hugo",
                            SupportDepartmentId = new Guid("122a1127-6afb-4cc6-976e-148eed423dcd")
                        },
                        new
                        {
                            SupportSpecialistId = new Guid("93575465-e1ba-4d73-a085-3d100001cfe7"),
                            Name = "Amira",
                            SupportDepartmentId = new Guid("122a1127-6afb-4cc6-976e-148eed423dcd")
                        });
                });

            modelBuilder.Entity("HelpDesk.Persistence.Models.SupportRequest", b =>
                {
                    b.HasOne("HelpDesk.Persistence.Models.SupportDepartment", "SupportDepartment")
                        .WithMany("SupportRequests")
                        .HasForeignKey("SupportDepartmentId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("HelpDesk.Persistence.Models.SupportSpecialist", "SupportSpecialist")
                        .WithMany("SupportRequests")
                        .HasForeignKey("SupportSpecialistId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("HelpDesk.Persistence.Models.SupportSpecialist", b =>
                {
                    b.HasOne("HelpDesk.Persistence.Models.SupportDepartment", "SupportDepartment")
                        .WithMany("SupportSpecialists")
                        .HasForeignKey("SupportDepartmentId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
